### ISSUE TITLE
CleanCellBoundaries error

### ISSUE THREAD

**Issue by kernco** [emanuega/MERlin#67]
I'm getting this error in the CleanCellBoundaries step of the pipeline. Is this a bug in the code, or something I'm doing wrong?
```
Traceback (most recent call last):
  File "C:\Users\ckern\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\ckern\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\ckern\merlin\merlin\__main__.py", line 3, in <module>
    merlin()
  File "c:\users\ckern\merlin\merlin\merlin.py", line 138, in merlin
    e.run(task, index=args.fragment_index)
  File "c:\users\ckern\merlin\merlin\core\executor.py", line 52, in run
    task.run(index)
  File "c:\users\ckern\merlin\merlin\core\analysistask.py", line 329, in run
    raise e
  File "c:\users\ckern\merlin\merlin\core\analysistask.py", line 320, in run
    self._run_analysis(fragmentIndex)
  File "c:\users\ckern\merlin\merlin\analysis\segment.py", line 168, in _run_analysis
    .read_features(currentFOV)
  File "c:\users\ckern\merlin\merlin\util\spatialfeature.py", line 500, in read_features
    self._load_feature_from_hdf5_group(featureGroup[k]))
  File "c:\users\ckern\merlin\merlin\util\spatialfeature.py", line 456, in _load_feature_from_hdf5_group
    zGroup['p_' + str(p)]))
  File "c:\users\ckern\merlin\merlin\util\spatialfeature.py", line 443, in _load_geometry_from_hdf5_group
    return geometry.shape(geometryDict)
  File "C:\Users\ckern\Anaconda3\lib\site-packages\shapely\geometry\geo.py", line 35, in shape
    if not ob["coordinates"]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

I'm attaching my analysis tasks file (renamed from .json to .txt because Github wouldn't let me attach a JSON). Let me know if you need any other information.

[with_segmentation.txt](https://github.com/emanuega/MERlin/files/5085987/with_segmentation.txt)

**Comment by seichhorn** [comment]
Sorry for the delay in getting to this. If you're still having an issue with this, could you tell me what version of Shapely is installed in your environment?

**Comment by kernco** [comment]
Shapely was version 1.7.0 when I had this error. I just did an update of my conda environment yesterday and shapely is now updated to 1.7.1. Should I try it again?

**Comment by seichhorn** [comment]
Try downgrading to shapely<1.7a2
